Booking/urls.py
from django.urls import path

from Booking.views import ScheduleView, ScheduleDayAPIView, ScheduleTimeAPIView, BookingAPIView, BookingAPIDelete

app_name = 'booking'

urlpatterns = [
    path('', ScheduleView.as_view(), name='schedule'),
    path('api/schedule/day/', ScheduleDayAPIView.as_view()),
    path('api/schedule/time/', ScheduleTimeAPIView.as_view()),
    path('api/booking/', BookingAPIView.as_view()),
    path('api/booking/<int:pk>', BookingAPIDelete.as_view()),
]

Cats/urls.py
from django.urls import path

from Cats.views import OurCatsView, CatsListAPIView, AdoptView, GiveView, GuardianshipView, AdopAPIView, GiveAPIView, \
    GuardianshipAPIView

app_name = 'cats'


urlpatterns = [
    path('our-cats/', OurCatsView.as_view(), name='our_cats'),
    path('adopt/', AdoptView.as_view(), name='adopt'),
    path('api/adopt/', AdopAPIView.as_view()),
    path('give/', GiveView.as_view(), name='give'),
    path('api/give/', GiveAPIView.as_view()),
    path('guardianship/', GuardianshipView.as_view(), name='guardianship'),
    path('api/guardianship/', GuardianshipAPIView.as_view()),
    path('api/cats/', CatsListAPIView.as_view(), name='cats-list'),
]

pawsAndCoffee/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from System.views import tr_handler500, tr_handler403, tr_handler404
from pawsAndCoffee import settings

handler403 = tr_handler403
handler404 = tr_handler404
handler500 = tr_handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),

    path('', include('Main.urls', namespace='main')),
    path('user/', include('Users.urls', namespace='users')),
    path('cats/', include('Cats.urls', namespace='cats')),
    path('calendar/', include('Booking.urls', namespace='booking')),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('bonus/', include('Bonuses.urls', namespace='bonuses'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(r'^403$', TemplateView.as_view(template_name='system/errors/error_page403.html')),
        re_path(r'^404$', TemplateView.as_view(template_name='system/errors/error_page404.html')),
        re_path(r'^500$', TemplateView.as_view(template_name='system/errors/error_page500.html')),
    ]

Bonuses/models.py
from django.db import models


class Coin(models.Model):
    count = models.PositiveIntegerField(verbose_name='Количество', default=0)

    def increased(self, discount, payment_amount, description):
        cost = (discount/100) * payment_amount
        self.count += cost
        History.objects.create(
            description=description,
            count=f'+{cost}',
            coin=self
        )
        return self.count

    def reducing(self, c):
        self.count -= c
        History.objects.create(
            description=f'Списание за бронь',
            count=f'-{c}',
            coin=self
        )
        return self.count

    def __str__(self):
        return f'{self.count}'

    class Meta:
        db_table = 'Bonuses'
        verbose_name = 'Мяукоин'
        verbose_name_plural = 'Мяукоины'


class History(models.Model):
    description = models.CharField(verbose_name='описание')
    count = models.CharField(verbose_name="Сумма начисления/списания")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')
    coin = models.ForeignKey(to=Coin, on_delete=models.CASCADE, verbose_name='Мяукоины пользователя',
                             blank=True, null=True, related_name='histories')

    class Meta:
        db_table = 'History'
        verbose_name = 'История'


class Coupon(models.Model):
    discount = models.PositiveIntegerField(verbose_name='Процент скидки')
    description = models.CharField(verbose_name='Описание')
    code = models.CharField(max_length=15, verbose_name='Код купона')

    def __str__(self):
        return f'{self.discount} - {self.description}'

    class Meta:
        db_table = 'Coupon'
        verbose_name = 'Промокод'
        verbose_name_plural = 'Промокоды'

Booking/models.py
import datetime

from django.db import models
from django.db.models import Q

from Users.models import CustomUser
from Main.models import Address
from Bonuses.models import Coupon


class Schedule(models.Model):
    TIME_CHOICE = [
        ('0', '10:00'),
        ('1', '11:00'),
        ('2', '12:00'),
        ('3', '13:00'),
        ('4', '15:00'),
        ('5', '16:00'),
        ('6', '17:00'),
        ('7', '18:00'),
    ]
    date = models.DateField(verbose_name='Дата посещения')
    time = models.CharField(choices=TIME_CHOICE, max_length=5, verbose_name='Время посещения')
    address = models.ForeignKey(to=Address, on_delete=models.CASCADE, verbose_name='Адресс кафе', default=1)
    cost = models.DecimalField(default=400.00, max_digits=5, decimal_places=2, verbose_name="Стандартная стоимость посещения")
    number_of_places = models.PositiveSmallIntegerField(verbose_name="Количество мест", default=5)

    def __str__(self):
        return f'Дата: {self.date}, время: {self.time}, места: {self.number_of_places}'

    def available_places(self):
        pass

    class Meta:
        db_table = 'Booking information'
        verbose_name = 'Информация о посещении'
        verbose_name_plural = 'Информация о посещених'
        indexes = [
            models.Index(fields=['date', 'time'])
        ]


class Booking(models.Model):
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date = models.DateField(verbose_name='Дата посещения')
    time = models.TimeField(verbose_name='Время посещения')
    address = models.ForeignKey(to=Address, on_delete=models.CASCADE, verbose_name='Адресс кафе', default=1)
    cost = models.DecimalField(default=200.00, max_digits=5, decimal_places=2, verbose_name="Cтоимость посещения")
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name='Количество человек')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    user = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь',
                             null=True, blank=True, related_name='booking', db_index=True)
    is_paid = models.BooleanField(default=False, verbose_name='Статус оплаты')
    phone = models.CharField(verbose_name='номер телефона')
    email = models.EmailField(max_length=254, verbose_name='Эл. почта')
    name = models.CharField(verbose_name='Имя посетителя')
    bonuses = models.IntegerField(default=0, verbose_name='Количество списаных бонусов во время оплаты')
    coupon = models.ForeignKey(to=Coupon, on_delete=models.CASCADE, verbose_name='Куопн', null=True, blank=True)

    def is_inactive(self):
        now = datetime.datetime.now().time()
        if self.date < datetime.date.today():
            return True
        elif self.date == datetime.date.today() and self.time < now:
            return True
        return False

    class Meta:
        db_table = 'Booking'
        verbose_name = 'Бронь'
        verbose_name_plural = 'Брони'
        indexes = [
            models.Index(fields=['session_key'], condition=Q(session_key__isnull=False), name='booking_session_key_not_null')
        ]

Users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models

from Bonuses.models import Coin


class CustomUserManager(BaseUserManager):
    def create_user(self, phone, email, username, password=None, birthday=None):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not password:
            raise ValueError("User must have a password")
        if not username:
            raise ValueError("User must have a username")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
        )
        user.username = username
        user.set_password(password)
        user.is_superuser = False
        user.is_staff = False
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, email, username, password=None, birthday=None, **kwargs):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not username:
            raise ValueError("User must have a username")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
            is_superuser=True,
            **kwargs
        )
        user.username = username
        user.set_password(password)
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_staffuser(self, phone, email, username, password=None, birthday=None, **kwargs):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not username:
            raise ValueError("User must have a username")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
            **kwargs
        )
        user.username = username
        user.set_password(password)
        user.is_superuser = False
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractUser, PermissionsMixin):
    ADMIN = 'admin'
    STAFF = 'staff'
    STATUS = [
        (ADMIN, 'Admin User'),
        (STAFF, 'Staff User'),
    ]

    username = models.CharField(unique=False, verbose_name='Имя пользователя', max_length=30)
    phone = models.CharField(unique=True, verbose_name='номер телефона', db_index=True)
    email = models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')
    coins = models.OneToOneField(to=Coin, on_delete=models.CASCADE, verbose_name='Мяукоины', null=True, blank=True, related_name='customuser')
    birthday = models.DateField(blank=True, null=True, verbose_name='дата рождения')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'username']

    objects = CustomUserManager()

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return f'{self.username}'

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

Booking/forms.py
from django import forms

from Booking.models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
         model = Booking
         fields = ['quantity', 'name', 'phone', 'email']
         widgets = {
             'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '5', 'value': '1', 'id': 'quantity'}),
             'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}),
             'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш адрес электронной почты'}),
             'phone': forms.TextInput(
                 attrs={'class': 'form-control', 'placeholder': '81112223333', 'id': 'id_phone'}),
         }

Booking/views.py
from django.conf import settings
from django.urls import reverse
from django.views.generic import TemplateView
from rest_framework import views, status, generics
from rest_framework.response import Response
from datetime import datetime

from Booking.models import Schedule, Booking
from Booking.serializers import ScheduleSerializer, BookingSerializer
from Booking.forms import BookingForm
from mixins.mixins import GetCacheMixin


class ScheduleView(GetCacheMixin, TemplateView):
    template_name = 'booking/schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Онлайн-запись'
        user = self.request.user
        if user.is_authenticated:
            data = {'name': user.username, 'phone': user.phone}
            form = BookingForm(data)
            context['form'] = form
        else:
            context['form'] = BookingForm
        return context


class ScheduleDayAPIView(views.APIView):
    def get(self, request):
        day = request.GET['day']
        today = datetime.today()
        date = datetime.strptime(f'{today.year}-{today.month}-{day}', '%Y-%m-%d').date()
        queryset = Schedule.objects.filter(date=date)
        serializer = ScheduleSerializer(queryset, many=True)
        return Response(serializer.data)


class ScheduleTimeAPIView(views.APIView):
    def get(self, request):
        day = request.GET['day']
        time = request.GET['time']
        today = datetime.today()
        date = datetime.strptime(f'{today.year}-{today.month}-{day}', '%Y-%m-%d').date()
        queryset = Schedule.objects.filter(date=date, time=time)
        serializer = ScheduleSerializer(queryset, many=True)
        return Response(serializer.data)


class BookingAPIDelete(generics.DestroyAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer


class BookingAPIView(views.APIView):

    def post(self, request):
        serializer = BookingSerializer(data=request.data)
        if not request.session.session_key:
            request.session.create()
        if serializer.is_valid():
            if request.user.is_authenticated:
                serializer.validated_data['user'] = request.user
                serializer.validated_data['session_key'] = None
                serializer.validated_data['birthday'] = request.user.birthday
            else:
                serializer.validated_data['user'] = None
                serializer.validated_data['session_key'] = request.session.session_key
            serializer.save()
            return Response(status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        booking = Booking.objects.all()
        return Response(BookingSerializer(booking, many=True).data)

Booking/templates/booking/modal_booking.html
{% load static %}

{% block modal %}
    <div class="modal fade" id="modal_booking" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form action="" method="post" class="txt-content" id="modal_booking_form">
                    {% csrf_token %}
                    <div class="modal-header my-modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                            <div id="modal_inf_booking"></div>
                            <div class="mb-3 px-2" id="quantity_form">
                                <label class="form-label mx-4" for="{{ form.quantity.id_for_lable }}">Количество человек<span class="txt-headline txt-select">*</span></label>
                                {{ form.quantity }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_quantity_feedback"></div>
                            </div>
                            <div class="mb-3 px-2">
                                <label class="form-label mx-4" for="{{ form.name.id_for_lable }}">Имя<span class="txt-headline txt-select">*</span></label>
                                {{ form.name }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_name_feedback"></div>
                            </div>
                            <div class="mb-3 px-2">
                                <label class="form-label mx-4" for="{{ form.phone.id_for_lable }}">Номер телефона<span class="txt-headline txt-select">*</span></label>
                                {{ form.phone }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_phone_feedback"></div>
                            </div>
                            <div class="mb-4 px-2">
                                <label class="form-label mx-4" for="{{ form.email.id_for_lable }}">Эл. почта<span class="txt-headline txt-select">*</span></label>
                                {{ form.email }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_email_feedback"></div>
                            </div>
                            <div class="mb-5 px-2">
                                <label class="form-label mx-4">Промокод</label>
                                <input class="form-control" id="id_code" placeholder="PROMOROD" name="code">
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_code_feedback"></div>
                            </div>
                            <div class="mb-3 px-2">
                                <div class="fs-min"><span class="txt-headline txt-select fs-min">*</span>Только для авторизованных пользователей!</div>
                                <p>
                                    <label class="form-label mx-2">Хотите оплатить бонусами?</label>
                                    <input type="checkbox" class="form-check-input" id="pay_coins_submit"
                                           {% if not request.user.is_authenticated%}
                                                disabled="True"
                                           {% endif %}>
                                </p>
                            </div>
                            <div class="pay_coins mb-4 px-2" id="{% if request.user.is_authenticated %}{{ request.user.pk }}_{{request.user.coins.pk}}{% endif %}" >
                                <div class="d-flex">
                                    <div class="col-7">
                                        <p>Количество ваших бонусов:</p>
                                        <div class="coins-block mx-5">
                                            <div>
                                                <img src="{% static 'images/catCoin.png' %}" class="img-coins z-2">
                                            </div>
                                            <div class="mx-2" id="inf_user_coins"></div>
                                        </div>
                                    </div>
                                    <div class="col-5" id="coin_form">
                                        <label class="form-label mx-4">Сколько мы спишем?</label>
                                        <input class="form-control" id="id_coins" type="number" name="coins">
                                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_coins_feedback"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3 px-2">
                                <label class="form-label txt-headline txt-select text-center fs-4 mx-4">К оплате: </label>
                                <div class="d-flex">
                                    <div class="col-6">
                                        <input id="id_cost" class="form-control" name="cost" value="200" readonly>
                                    </div>
                                    <div class="col-2 px-3 pt-1 txt-headline txt-select" id="multiply_quantity">Х1</div>
                                    <div class="col-2 pt-1 txt-headline txt-select" id="minus_coin"></div>
                                </div>
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_cost_feedback"></div>
                            </div>
                    </div>
                    <div class="modal-footer my-modal-header">
                        <button type="submit" class="btn btn-dark btn-block">Перейти к оплате</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Booking/templates/booking/schedule.html
{% extends 'base.html' %}
{% load static %}

{% block add_css %}
    <link rel="stylesheet" href="{% static "css/calendar.css" %}">
{% endblock %}

{% block content %}
<div class="container pt-4">
    <h2 class="text-center txt-headline my-5">Запись на <span class="calendar-current-date"></span></h2>
    <h3 class="text-center txt-content fs-5 pb-3">Стоимость <span class="fs-3 txt-headline txt-select">часа</span>
        посещения для <span class="fs-3 txt-headline txt-select">одного</span> человека составляет
        <span class="fs-3 txt-headline txt-select" name="cost"></span>!</h3>
    <div class="container pt-4 pb-5">
        <div class="row">
            <div class="col-6 d-flex justify-content-center">
                <div class="calendar-container py-2 my-3 px-auto">
                    <div class="calendar-body">
                        <ul class="calendar-weekdays">
                            <li>Пн</li>
                            <li>Вт</li>
                            <li>Ср</li>
                            <li>Чт</li>
                            <li>Пт</li>
                            <li>Сб</li>
                            <li>Вс</li>
                        </ul>
                        <ul class="calendar-dates"></ul>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="time-container pt-1">
                    <h3 class="txt-headline text-center mb-4 fs-3">Свободные о<span style="color: #fd708d">кошки</span>:</h3>
                    <div class="time-body">
                        <div class="container">
                            <div id="no_selected">
                                <div class="position-relative">
                                    <h5 class="text-center pt-4 fs-3 txt-content z-2">Выберите нужную дату</h5>
                                    <img class="underline_img z-1" src="{% static 'images/underline.png' %}" width="310px">
                                    <img class="blue_arrow" src="{% static 'images/blue_arrow.png' %}" width="310px">
                                </div>
                            </div>
                            <div class="row row-cols-2 mx-n1" id="choice_times">
                            </div>
                            {% include 'booking/modal_booking.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block add_scripts %}
    <script src="{% static "js/Main/get_information.js" %}"></script>
    <script src="{% static "js/Booking/calendar.js" %}"></script>
    <script src="{% static "js/Booking/form.js" %}"></script>
{% endblock %}