Cats/urls.py
from django.urls import path

from Cats.views import OurCatsView, CatsListAPIView, AdoptView, GiveView, GuardianshipView, AdopAPIView, GiveAPIView, \
    GuardianshipAPIView

app_name = 'cats'


urlpatterns = [
    path('our-cats/', OurCatsView.as_view(), name='our_cats'),
    path('adopt/', AdoptView.as_view(), name='adopt'),
    path('api/adopt/', AdopAPIView.as_view()),
    path('give/', GiveView.as_view(), name='give'),
    path('api/give/', GiveAPIView.as_view()),
    path('guardianship/', GuardianshipView.as_view(), name='guardianship'),
    path('api/guardianship/', GuardianshipAPIView.as_view()),
    path('api/cats/', CatsListAPIView.as_view(), name='cats-list'),
]

pawsAndCoffee/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from System.views import tr_handler500, tr_handler403, tr_handler404
from pawsAndCoffee import settings

handler403 = tr_handler403
handler404 = tr_handler404
handler500 = tr_handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),

    path('', include('Main.urls', namespace='main')),
    path('user/', include('Users.urls', namespace='users')),
    path('cats/', include('Cats.urls', namespace='cats')),
    path('calendar/', include('Booking.urls', namespace='booking')),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('bonus/', include('Bonuses.urls', namespace='bonuses'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(r'^403$', TemplateView.as_view(template_name='system/errors/error_page403.html')),
        re_path(r'^404$', TemplateView.as_view(template_name='system/errors/error_page404.html')),
        re_path(r'^500$', TemplateView.as_view(template_name='system/errors/error_page500.html')),
    ]

Cats/forms.py
from django import forms

from Cats.models import FormForAdopt, FormForGive, FormForGuardianship


class AdoptForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat_name'].empty_label = 'Котик не выбран'

    class Meta:
        model = FormForAdopt
        fields = ['name', 'phone', 'email', 'social', 'cat_name', 'why_this_cat', 'children', 'has_pet', 'pets']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '81112223333', 'id': 'id_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш адрес электронной почты'}),
            'social': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Оставьте здесь ссылку на вашу страницу'}),
            'cat_name': forms.Select(attrs={'class': "form-select"}),
            'why_this_cat': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Расскажите почему выбрали именно этого кота'}),
            'children': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'has_pet': forms.CheckboxInput(attrs={'class': 'form-check-input', 'name': 'has_pet'}),
            'pets': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Расскажите какие у вас есть еще животные'})
        }


class GiveForm(forms.ModelForm):
    class Meta:
        model = FormForGive
        fields = ['name', 'phone', 'email', 'social', 'cat_name', 'birthday', 'character', 'features', 'gender', 'type_of_help', 'reason', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}),
            'cat_name': forms.TextInput(attrs={'class': "form-control", 'placeholder': 'Введите имя вашего котика'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(000) 000-0000', 'id': 'id_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш адрес электронной почты'}),
            'social': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Оставьте здесь ссылку на вашу страницу'}),
            'birthday': forms.DateInput(attrs={'class': "form-control", 'type': 'date'}),
            'character': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Опишите характер котика'}),
            'features': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Расскажите есть ли у котика какие-то особенности, '
                                                                                      'о которых мы должны знать'}),
            'gender': forms.RadioSelect(attrs={'class': 'form-check-input'}),
            'type_of_help': forms.RadioSelect(attrs={'class': 'form-check-input'}),
            'reason': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Напишите по какой причине вы решили отдать нам котика'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Добавьте фотографию котика'})
        }


class GuardianshipForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat_name'].empty_label = 'Котик не выбран'

    class Meta:
        model = FormForGuardianship
        fields = ['name', 'phone', 'email', 'social', 'cat_name', 'amount_of_money', 'interval']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(000) 000-0000', 'id': 'id_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш адрес электронной почты'}),
            'social': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Оставьте здесь ссылку на вашу страницу'}),
            'cat_name': forms.Select(attrs={'class': "form-select"}),
            'amount_of_money': forms.Select(attrs={'class': 'form-select'}),
            'interval': forms.Select(attrs={'class': 'form-select'})
        }

Cats/views.py
import json

from django.conf import settings
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from rest_framework import generics, views, status
from rest_framework.response import Response

from Cats.forms import AdoptForm, GiveForm, GuardianshipForm
from Cats.models import Cats, FormForGuardianship, FormForAdopt, FormForGive
from Cats.serializers import CatsSerializer, GuardianshipSerializer, AdoptSerializer, GiveSerializer


class CatsListAPIView(generics.ListAPIView):
    queryset = Cats.objects.all()
    serializer_class = CatsSerializer


class OurCatsView(View):
    context = {
        'title': 'Наши коты'
    }

    def get(self, request):
        cats = Cats.objects.all()
        paginator = Paginator(cats, 2)
        page = request.GET.get('page', 1)
        page_obj = paginator.get_page(int(page))
        self.context['cats'] = page_obj
        return render(request, 'cats/our_cats.html', self.context)


class AdopAPIView(views.APIView):
    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def post(self, request):
        serializer = AdoptSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            if self.is_ajax():
                valid_data = []
                for field in serializer.validated_data:
                    valid_data.append(field)
                response_data = {
                    'message': 'Заявка была принята',
                    'valid_data': json.dumps(valid_data),
                }
                return JsonResponse(response_data)
            return Response(status=status.HTTP_201_CREATED)
        else:
            if self.is_ajax():
                errors = {}
                for field in serializer.errors:
                    errors[field] = serializer.errors[field][0].title()
                valid_data = []
                for field in serializer.data:
                    if field not in errors:
                        valid_data.append(field)
                response_data = {
                    'result': 'error',
                    'errors': json.dumps(errors),
                    'valid_data': json.dumps(valid_data),
                    'message': 'Заявка не была отправлена! Проверьте правильность заполнения полей'
                }
                return JsonResponse(response_data)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        adopt = FormForAdopt.objects.all()
        return Response({'post': AdoptSerializer(adopt, many=True).data})


class AdoptView(View):
    context = {
        'title': 'Приютить котика',
    }

    def get(self, request):
        user = request.user
        if user.is_authenticated:
            data = {'name': user.username, 'phone': user.phone, 'email': user.email}
            form = AdoptForm(data)
        else:
            form = AdoptForm
        self.context['form'] = form
        return render(request, 'cats/adopt.html', context=self.context)


class GiveAPIView(views.APIView):
    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def post(self, request):
        serializer = GiveSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            if self.is_ajax():
                valid_data = []
                for field in serializer.validated_data:
                    valid_data.append(field)
                response_data = {
                    'message': 'Заявка была принята',
                    'valid_data': json.dumps(valid_data),
                }
                return JsonResponse(response_data)
            return Response(status=status.HTTP_201_CREATED)
        else:
            if self.is_ajax():
                errors = {}
                for field in serializer.errors:
                    errors[field] = serializer.errors[field][0].title()
                valid_data = []
                for field in serializer.data:
                    if field not in errors:
                        valid_data.append(field)
                response_data = {
                    'result': 'error',
                    'errors': json.dumps(errors),
                    'valid_data': json.dumps(valid_data),
                    'message': 'Заявка не была отправлена! Проверьте правильность заполнения полей'
                }
                return JsonResponse(response_data)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        give = FormForGive.objects.all()
        return Response({'post': GiveSerializer(give, many=True).data})


class GiveView(View):
    context = {
        'title': 'Отдать котика',
    }

    def get(self, request):
        user = request.user
        if user.is_authenticated:
            data = {'name': user.username, 'phone': user.phone, 'email': user.email}
            form = GiveForm(data)
        else:
            form = GiveForm
        self.context['form'] = form
        return render(request, 'cats/give.html', context=self.context)


class GuardianshipView(View):
    context = {
        'title': 'Опекунство',
    }

    def get(self, request):
        user = request.user
        if user.is_authenticated:
            data = {'name': user.username, 'phone': user.phone, 'email': user.email}
            form = GuardianshipForm(data)
        else:
            form = GuardianshipForm
        self.context['form'] = form
        return render(request, 'cats/guardianship.html', context=self.context)


class GuardianshipAPIView(views.APIView):
    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def post(self, request):
        serializer = GuardianshipSerializer(data=request.data)
        if not request.session.session_key:
            request.session.create()
        if serializer.is_valid():
            if request.user.is_authenticated:
                serializer.validated_data['user'] = request.user
                serializer.validated_data['session_key'] = None
            else:
                serializer.validated_data['user'] = None
                serializer.validated_data['session_key'] = request.session.session_key
            serializer.save()
            if self.is_ajax():
                valid_data = []
                for field in serializer.validated_data:
                    valid_data.append(field)
                response_data = {
                    'message': 'Заявка была принята',
                    'valid_data': json.dumps(valid_data),
                }
                return JsonResponse(response_data)
            return Response(status=status.HTTP_201_CREATED)
        else:
            if self.is_ajax():
                errors = {}
                for field in serializer.errors:
                    errors[field] = serializer.errors[field][0].title()
                valid_data = []
                for field in serializer.data:
                    if field not in errors:
                        valid_data.append(field)
                response_data = {
                    'result': 'error',
                    'errors': json.dumps(errors),
                    'valid_data': json.dumps(valid_data),
                    'message': 'Заявка не была отправлена! Проверьте правильность заполнения полей'
                }
                return JsonResponse(response_data)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        guardianship = FormForGuardianship.objects.all()
        return Response(GuardianshipSerializer(guardianship, many=True).data)

Cats/templates/cats/adopt.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2 class="txt-headline text-center my-5">Как приютить котика из нашего кафе?</h2>
    <ul class="txt-content">
        <li class="list-img list-item py-2">Кошка отдается вам <span class="txt-headline txt-select">воспитанной, социализированной, привитой,с
            ветеринарным паспортом, приученной к лотку, обработанной от внешних и внутренних паразитов, чипированной, стерилизованной</span>.
        </li>
        <li class="list-img list-item py-2">Чтобы взять ее в дом, достаточно <a href="#cat_forms" class=" a-default txt-headline txt-select">
            заполнить анкету</a> расположенную ниже.
        </li>
        <li class="list-img list-item py-2">Мы ответим на вашу заявку в <span class="txt-headline txt-select">течение семи дней</span>.</li>
        <li class="list-img list-item py-2">Мы можем вам <span class="txt-headline txt-select">отказать</span>.
            При рассмотрении всех кандидатов, выборм падает на того, кто сможет, стать хорошей семьей именно для выбранной кошки.
            Если мы видим, что <span class="txt-headline txt-select">кошке может быть некомфортно с вами</span>
            или существуют какие-либо <span class="txt-headline txt-select">другие препятствующие причины</span>, то мы можем вам отказать.
            Сообщение о принятом нами решении <span class="txt-headline txt-select">придет вам на почту или телефон</span>.
        </li>
        <li class="list-img list-item py-2">Если вы нам понравитесь, то <span class="txt-headline txt-select">проводится с
            вами встреча (лично или удаленно)</span>, для дальнейшего знакомства.</li>
        <li class="list-img list-item py-2">При положительном рассмотрении анкеты и собеседования, мы
            <span class="txt-headline txt-select">заключаем с вами договор</span>, по которому мы оказываем вам поддержку в каких-либо случаях
            с котом, а также просим вас не причинять коту или кошке ничего плохого.
            Передаем вам ветеринарный анализ и текущие анализы животного. А позже доставляем котика вам домой.</li>
        <li class="list-img list-item py-2">Пожалуйста, обратите внимание, что <span class="txt-headline txt-select">
            все операции пристройства кошки бесплатны</span>.</li>
    </ul>
    <div class="row pt-5">
        <div class="container pt-4">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white rounded form-cats mb-5">
                    <h2 class="text-white text-center txt-headline pt-4">Анкета для усыновления</h2>
                    <div class="bg-white p-4 mx-5 mb-5 mt-3">
                        <form action="{% url 'cats:adopt' %}" id="cat_forms" method="post">
                            {% csrf_token %}
                            <div class="d-flex flex-column align-items-center txt-content mt-4">
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.name.id_for_lable }}">Ваше имя<span class="txt-headline txt-select">*</span></label>
                                    {{ form.name }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_name_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.phone.id_for_lable }}">Телефон<span class="txt-headline txt-select">*</span></label>
                                    {{ form.phone }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_phone_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.email.id_for_lable }}">Эл. почта<span class="txt-headline txt-select">*</span></label>
                                    {{ form.email }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_email_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.social.id_for_lable }}">Ссылки на соц. сети</label>
                                    {{ form.social }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_social_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.cat_name.id_for_lable }}">Выберите котика<span class="txt-headline txt-select">*</span></label>
                                    {{ form.cat_name }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_cat_name_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-4">
                                    <label class="form-label mx-4" for="{{ form.why_this_cat.id_for_lable }}">Почему именно этот котик?<span class="txt-headline txt-select">*</span></label>
                                    {{ form.why_this_cat }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_why_this_cat_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-1">
                                    {{ form.children }}
                                    <label class="form-label mx-2" for="{{ form.children.id_for_lable }}">У вас есть дети?<span class="txt-headline txt-select">*</span></label>
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_children_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                        {{ form.has_pet }}
                                        <label class="form-label mx-2" for="{{ form.has_pet.id_for_lable }}">У вас есть животные?<span class="txt-headline txt-select">*</span></label>
                                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_has_pet_feedback"></div>
                                    </div>
                                <div class="col-md-10 mb-3" id="AnotherPets">
                                    <label class="form-label mx-4" for="{{ form.pets.id_for_lable }}">Какие животные у вас еще есть?<span class="txt-headline txt-select">*</span></label>
                                    {{ form.pets }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_pets_feedback"></div>
                                </div>
                                <button type="submit" class="btn btn-dark btn-block my-4">Отправить заявку</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block add_scripts %}
    <script src="{% static "js/js-msg.js" %}"></script>
    <script src="{% static "js/Cats/form.js" %}"></script>
{% endblock %}

Cats/templates/cats/guardianship.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2 class="txt-headline text-center my-5">Как взять котика под свою опеку?</h2>
    <p class="txt-content px-3">Если вы не можете взять кошку в семью, но хотите ей очень помочь, то у нас есть для вас прекрасное предложение - опекунство!</p>
    <ul class="txt-content">
        <li class="list-img list-item py-2">Вы <span class="txt-headline txt-select">подписываетесь </span>на платеж от 400₽ в месяц;</li>
        <li class="list-img list-item py-2">На эту сумму можно <span class="txt-headline txt-select">бесплатно
            посещать своего любимца в котокафе</span>;</li>
        <li class="list-img list-item py-2"><span class="txt-headline txt-select">Как мы тратим ваши деньги?</span> — Мы делаем все,
            чтобы быстрее найти семью для этого котика, <span class="txt-headline txt-select">продвигаем в социальных сетях и приглашаем фотографов для качественных фото</span>;</li>
        <li class="list-img list-item py-2">В любой момент вы можете <span class="txt-headline txt-select">отменить</span> свою подписку
            в <span class="txt-headline txt-select">личном кабинете</span>
            или <span class="txt-headline txt-select">связаться с нами</span>;</li>
        <li class="list-img list-item py-2">Как только котик находит семью, мы <span class="txt-headline txt-select">прекращаем подписку
            и упоминаем вас в посте-отчете.</span></li>
    </ul>
    <div class="row pt-5">
        <div class="container pt-4">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white rounded form-cats mb-5">
                    <h2 class="text-white text-center txt-headline pt-4">Оформление подписки</h2>
                    <div class="bg-white p-4 mx-5 mb-5 mt-3">
                        <form action="{% url 'cats:adopt' %}" id="cat_forms" method="post">
                            {% csrf_token %}
                            <div class="d-flex flex-column align-items-center txt-content mt-4">
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.name.id_for_lable }}">Ваше имя<span class="txt-headline txt-select">*</span></label>
                                    {{ form.name }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_name_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.phone.id_for_lable }}">Телефон<span class="txt-headline txt-select">*</span></label>
                                    {{ form.phone }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_phone_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.email.id_for_lable }}">Эл. почта<span class="txt-headline txt-select">*</span></label>
                                    {{ form.email }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_email_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.social.id_for_lable }}">Ссылки на соц. сети</label>
                                    {{ form.social }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_social_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.cat_name.id_for_lable }}">Выберите котика<span class="txt-headline txt-select">*</span></label>
                                    {{ form.cat_name }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_cat_name_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-4">
                                    <label class="form-label mx-4" for="{{ form.amount_of_money.id_for_lable }}">Стоимость подписки<span class="txt-headline txt-select">*</span></label>
                                    {{ form.amount_of_money }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_amount_of_money_feedback"></div>
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label class="form-label mx-4" for="{{ form.interval.id_for_lable }}">Период<span class="txt-headline txt-select">*</span></label>
                                    {{ form.interval }}
                                    <div class="invalid-feedback" style="text-transform: lowercase" id="id_interval_feedback"></div>
                                </div>
                                <button type="submit" class="btn btn-dark btn-block my-4">Перейти к оплате</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block add_scripts %}
    <script src="{% static "js/js-msg.js" %}"></script>
    <script src="{% static "js/Cats/form.js" %}"></script>
{% endblock %}

Cats/templates/cats/our_cats.html
{% extends 'base.html' %}
{% load static %}

{% block add_css %}
    <link rel="stylesheet" href="{% static "css/4_columns.css" %}">
{% endblock %}

{% block content %}
<div class="container">
    <h2 class="txt-headline text-center pt-5">Наши мурчащие сотрудники<img height="50rem" src="{% static "/images/icons8-cat-footprint-64.png" %}"></h2>
    <div class="my-4 text-center txt-content pb-1">На этой странице вы можете <span class="text-wavy">познакомиться поближе</span> с нашими пушистыми красавцами и красавицами!
        В нашем Кото-кафе мы не только заботимся о наших котах, но и приглашаем вас стать частью их жизни. Если вы влюбились
        в одного из наших пушистиков и <span class="text-wavy">хотите подарить ему дом</span>, мы будем рады помочь вам в этом.
        У нас есть <span class="text-wavy">возможность усыновления</span>, и мы ищем любящие семьи для наших котиков. Если вам по каким-то причинам не подходит этот вариант,
        но желание помочь все еще есть, то <span class="text-wavy">вы можете оформить опекунство</span>.
    </div>
    <div class="d-flex justify-content-center pb-3 pt-3">
        <a href="{% url 'cats:adopt' %}" class="mx-4 py-2 btn btn-primary btn-bg-color fs-4">взять в семью</a>
        <a href="{% url 'cats:give' %}" class="mx-4 py-2 btn btn-primary btn-bg-color fs-4">отдать</a>
        <a href="{% url 'cats:guardianship' %}" class="mx-4 py-2 btn btn-primary btn-bg-color fs-4">взять под опеку</a>
    </div>
    <div class="block-cats my-5 p-3">
        <div class="row row-cols-2">
            {% for cat in cats %}
                <div class="col-6 d-flex">
                    <div class="col-6 d-flex me-2">
                        <img class="align-self-center cat-img" src="{{ cat.image }}">
                    </div>
                    <div class="col-6 container-col my-4 px-3">
                        <p class="text-center pt-3 txt-headline txt-select-cat">
                            <img class="cat-name-img rotate" src="{% static "/images/icons8-cat-footprint-64.png" %}">
                            {{ cat.name }}
                            <img class="cat-name-img" src="{% static "/images/icons8-cat-footprint-64.png" %}">
                        </p>
                        <p class="txt-content">{{ cat.description }}</p>
                        <p class="txt-content">День рождения: <span class="txt-headline txt-select-cat">{{ cat.birthday }}</span></p>
                        <div class="d-flex">
                            <p class="txt-content">Пол: <span class="txt-headline txt-select-cat">{{ cat.gender }}</span></p>
                            <p class="txt-content px-3">Порода: <span class="txt-headline txt-select-cat">{{ cat.breed }}</span></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="text-center mb-5">
        <ul class="custom-pagination">
            <li class="custom-page-item {% if not cats.has_previous %} disabled {% endif %}">
                <a class="page-link"
                   href="{% if cats.has_previous %}?page={{ cats.previous_page_number }}{% else %} # {% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li>
                {% for page in cats.paginator.page_range %}
                    {% if cats.number == page %}
                        <li class="custom-page-item active">
                            <span class="page-link">{{ page }}</span>
                        </li>
                    {% elif page >= cats.number|add:-2 and page <= cats.number|add:2  %}
                        <li class="custom-page-item">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor%}
            </li>
            <li class="custom-page-item {% if not cats.has_next %} disabled {% endif %}">
                <a class="page-link"
                   href="{% if cats.has_next %}?page={{ cats.next_page_number }}{% else %} # {% endif %}"
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}