Booking/urls.py
from django.urls import path

from Booking.views import ScheduleView, ScheduleDayAPIView, ScheduleTimeAPIView, BookingAPIView, BookingAPIDelete

app_name = 'booking'

urlpatterns = [
    path('', ScheduleView.as_view(), name='schedule'),
    path('api/schedule/day/', ScheduleDayAPIView.as_view()),
    path('api/schedule/time/', ScheduleTimeAPIView.as_view()),
    path('api/booking/', BookingAPIView.as_view()),
    path('api/booking/<int:pk>', BookingAPIDelete.as_view()),
]

Cats/urls.py
from django.urls import path

from Cats.views import OurCatsView, CatsListAPIView, AdoptView, GiveView, GuardianshipView, AdopAPIView, GiveAPIView, \
    GuardianshipAPIView

app_name = 'cats'


urlpatterns = [
    path('our-cats/', OurCatsView.as_view(), name='our_cats'),
    path('adopt/', AdoptView.as_view(), name='adopt'),
    path('api/adopt/', AdopAPIView.as_view()),
    path('give/', GiveView.as_view(), name='give'),
    path('api/give/', GiveAPIView.as_view()),
    path('guardianship/', GuardianshipView.as_view(), name='guardianship'),
    path('api/guardianship/', GuardianshipAPIView.as_view()),
    path('api/cats/', CatsListAPIView.as_view(), name='cats-list'),
]

Users/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from Users.views import (UserProfileTemplateView, UserChangeProfileView, UserLoginRegView, UserAccountAPIView, UserLogoutView,
                         UserResetPasswordView, UserResetNewPasswordView, UserUpdateInfAboutPaymentsView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginRegView.as_view(), name='page_login'),
    path('update/', UserUpdateInfAboutPaymentsView.as_view(), name='update'),
    path('email/reset/', UserResetPasswordView.as_view(), name='reset_password'),
    path('password/reset/confirm/<str:uid>/<str:token>/', UserResetNewPasswordView.as_view(), name='new_password'),
    path('profile/', UserProfileTemplateView.as_view(), name='profile'),
    path('profile/change/', UserChangeProfileView.as_view(), name='change_profile'),
    path('logout/', UserLogoutView.as_view(), name='logout_delToken'),
    path('api/auth/my/profile/', UserAccountAPIView.as_view(), name='account'),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^api/auth/', include('djoser.urls.authtoken')),
]

pawsAndCoffee/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from System.views import tr_handler500, tr_handler403, tr_handler404
from pawsAndCoffee import settings

handler403 = tr_handler403
handler404 = tr_handler404
handler500 = tr_handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),

    path('', include('Main.urls', namespace='main')),
    path('user/', include('Users.urls', namespace='users')),
    path('cats/', include('Cats.urls', namespace='cats')),
    path('calendar/', include('Booking.urls', namespace='booking')),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('bonus/', include('Bonuses.urls', namespace='bonuses'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(r'^403$', TemplateView.as_view(template_name='system/errors/error_page403.html')),
        re_path(r'^404$', TemplateView.as_view(template_name='system/errors/error_page404.html')),
        re_path(r'^500$', TemplateView.as_view(template_name='system/errors/error_page500.html')),
    ]

Users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models

from Bonuses.models import Coin


class CustomUserManager(BaseUserManager):
    def create_user(self, phone, email, username, password=None, birthday=None):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not password:
            raise ValueError("User must have a password")
        if not username:
            raise ValueError("User must have a username")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
        )
        user.username = username
        user.set_password(password)
        user.is_superuser = False
        user.is_staff = False
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, email, username, password=None, birthday=None, **kwargs):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not username:
            raise ValueError("User must have a username")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
            is_superuser=True,
            **kwargs
        )
        user.username = username
        user.set_password(password)
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_staffuser(self, phone, email, username, password=None, birthday=None, **kwargs):
        if not phone:
            raise ValueError('User must have an phone')
        if not email:
            raise ValueError('User must have an email')
        if not username:
            raise ValueError("User must have a username")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            phone=phone,
            birthday=birthday,
            **kwargs
        )
        user.username = username
        user.set_password(password)
        user.is_superuser = False
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractUser, PermissionsMixin):
    ADMIN = 'admin'
    STAFF = 'staff'
    STATUS = [
        (ADMIN, 'Admin User'),
        (STAFF, 'Staff User'),
    ]

    username = models.CharField(unique=False, verbose_name='Имя пользователя', max_length=30)
    phone = models.CharField(unique=True, verbose_name='номер телефона', db_index=True)
    email = models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')
    coins = models.OneToOneField(to=Coin, on_delete=models.CASCADE, verbose_name='Мяукоины', null=True, blank=True, related_name='customuser')
    birthday = models.DateField(blank=True, null=True, verbose_name='дата рождения')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'username']

    objects = CustomUserManager()

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return f'{self.username}'

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

Users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordResetForm, SetPasswordForm
from django import forms
from django.core.exceptions import ValidationError

from Users.models import CustomUser


def validate_password(pas, re_pas):
    if re_pas != pas:
        raise ValidationError("Пароли не совпадают")
    else:
        return re_pas


class UserRegForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phone', 'birthday', 'password', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control inpt', 'placeholder': 'Введите ваш логин'}),
            'phone': forms.TextInput(attrs={'class': 'form-control inpt', 'placeholder': '81112223333', 'id': 'id_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control inpt', 'placeholder': 'Введите ваш адрес эл. почты'}),
        }

    birthday = forms.DateField(widget=forms.DateInput(attrs={'class': "form-control inpt", 'type': 'date'}), required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control inpt",
                                                                  'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control inpt", 'placeholder': 'Повторите пароль'}))


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control inpt', 'placeholder': 'Введите ваш адрес эл. почты'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control inpt", 'placeholder': 'Введите пароль'}))


class UserChangeProfileForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phone', 'birthday', 'current_password', 'new_password', 're_new_password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите новый логин'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(000) 000-0000', 'id': 'id_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите новый адрес эл. почты'}),
        }

    birthday = forms.DateField(widget=forms.DateInput(attrs={'class': "form-control", 'type': 'date'}), required=False)
    current_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': "form-control",
                                                                  'placeholder': 'Введите текущий пароль'}))
    new_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': "form-control",
                                                                                 'placeholder': 'Введите новый пароль'}))
    re_new_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': "form-control",
                                                                  'placeholder': 'Подтвердите пароль'}))


class UserResetForm(PasswordResetForm):
    class Meta:
        model = CustomUser
        fields = ['email']

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите адрес эл. почты'}))


class UserSetPasswordForm(SetPasswordForm):
    class Meta:
        model = CustomUser
        fields = ['new_password', 're_new_password']

    new_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': "form-control",
                                                                                     'placeholder': 'Введите новый пароль'}))
    re_new_password = forms.CharField(required=False, validators=[validate_password],
                                      widget=forms.PasswordInput(attrs={'class': "form-control", 'placeholder': 'Подтвердите новый пароль'}))

Users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from djoser.email import BaseDjoserEmail
from django.test import Client
from rest_framework import viewsets, views, status
from rest_framework.decorators import action
from rest_framework.response import Response

from Users.forms import UserLoginForm, UserChangeProfileForm, UserRegForm, UserResetForm, UserSetPasswordForm
from Users.serializers import UserProfileSerializer, UserUpdateSerializer
from Users.models import CustomUser
from Booking.models import Booking
from Cats.models import FormForGuardianship
from mixins.mixins import GetCacheMixin, GetAuthTokenMixin
from permissions.permissions import IsAdminOrAuthenticatedReadOnly
from Users.tasks import custom_reset_password


class UserLoginRegView(View):
    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    context = {
        'title': 'Авторизация'
    }

    def get(self, request):
        form = UserRegForm
        form1 = UserLoginForm
        self.context['form1'] = form1
        self.context['form'] = form
        return render(request, 'users/login.html', context=self.context)

    def post(self, request):
        if self.is_ajax():
            token = request.POST.get('auth-token')
            response = render(request, 'users/login.html', context=self.context)
            response.set_cookie('auth-token', token)
            return response
        return HttpResponse(status=500)


class UserResetPasswordView(View):
    context = {
        'title': 'Восстановление пароля'
    }

    def get(self, request):
        form = UserResetForm
        self.context['form'] = form
        return render(request, 'users/reset_password.html', context=self.context)


class UserResetNewPasswordView(View):
    context = {
        'title': 'Установка нового пароля'
    }

    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def get(self, request, **kwargs):
        user = request.user
        form = UserSetPasswordForm(user=user)
        self.context['form'] = form
        self.context['uid'] = kwargs.get('uid')
        self.context['token'] = kwargs.get('token')
        return render(request, 'users/reset_new_password.html', context=self.context)


class CustomPasswordResetEmail(BaseDjoserEmail):
    template_name = "email/password_reset.html"

    def get_context_data(self, request):
        email = request.GET.get('email')
        try:
            user = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            return JsonResponse({'email': 'Пользователя с такой почтой не найдено'})

        reset_email_context = custom_reset_password.delay(user=user, request=request)
        new_values = {key: value for (key, value) in reset_email_context.items()}

        context = super().get_context_data()
        context.update(new_values)

        return context


class UserProfileTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['title'] = 'Личный кабинет'
        return context

# class UserProfileView(LoginRequiredMixin, GetCacheMixin, GetAuthTokenMixin, View):
#     context = {
#         'title': 'Личный кабинет'
#     }

#     def get(self, request, *args, **kwargs):
#         user_pk = request.user.pk
#         return render(request, 'users/profile.html')


class UserChangeProfileView(LoginRequiredMixin, View):
    context = {
        'title': 'Изменить профиль'
    }

    def get(self, request):
        user = request.user
        form = UserChangeProfileForm(instance=user)
        self.context['form'] = form
        return render(request, 'users/change_profile.html', context=self.context)


class UserUpdateInfAboutPaymentsView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
            booking = Booking.objects.filter(phone=user.phone)
            guardianship = FormForGuardianship.objects.filter(phone=user.phone)
            if booking:
                for data in booking:
                    if data.is_paid:
                        data.user = user
                        data.save()
            if guardianship:
                for data in guardianship:
                    if data.is_paid:
                        data.user = user
                        data.save()
            return redirect(reverse('users:profile'))
        else:
            messages.warning(request, 'На сервере произошла ошибка!\n Попробуйте авторизоваться еще раз')
            return redirect(reverse('users:page_login'))


class UserLogoutView(View):
    def is_ajax(self):
        return self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def post(self, request):
        if self.is_ajax():
            response = HttpResponseRedirect(reverse('main:index'))
            request.delete_cookie = True
            return response
        return HttpResponse(status=500)


class UserAccountAPIView(views.APIView):

    def get(self, request):
        user_id = request.user.pk
        data = CustomUser.objects.get(id=user_id)
        return Response(UserProfileSerializer(data).data)

    def put(self, request):
        serializer = UserUpdateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

Users/templates/users/change_profile.html
{% extends 'base.html' %}
{% load static %}

{% block add_css %}
    <link rel="stylesheet" href="{% static "css/users_forms.css" %}">
{% endblock %}

{% block content %}
<div class="container">
    <img src="{% static 'images/catjpg.jpg' %}" class="bg-profile">
    <div class="my-container mt-3" style="width: 740px; left: 49%">
        <h3 class="txt-headline text-center pt-5">Изменить данные профиля</h3>
        <div class="row justify-content-center pt-4 txt-content">
            <div class="col-md-7 gx-4">
                <form action="{% url 'users:change_profile' %}" method="post" class="txt-content inpt pt-3" id="user_forms">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label class="form-label mx-4" for="{{ form.username.id_for_lable }}">Логин<span class="txt-headline txt-select">*</span></label>
                        {{ form.username }}
                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_username_feedback"></div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label mx-4" for="{{ form.phone.id_for_lable }}">Номер телефона<span class="txt-headline txt-select">*</span></label>
                        {{ form.phone }}
                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_phone_feedback"></div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label mx-4" for="{{ form.email.id_for_lable }}">Эл. почта<span class="txt-headline txt-select">*</span></label>
                        {{ form.email }}
                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_email_feedback"></div>
                    </div>
                    <div class="col-md-6 mt-2">
                        <label class="form-label mx-4" for="{{ form.birthday.id_for_lable }}">Дата рождения</label>
                        {{ form.birthday }}
                        <div class="invalid-feedback" style="text-transform: lowercase" id="id_birthday_feedback"></div>
                    </div>
                    <div class="row justify-content-center pt-4 mt-3">
                        <a id="BtnChangePassword" class="btn btn-dark btn-block col-5">Изменить пароль</a>
                    </div>
                    <div id="ChangePassword" class="col-md-12">
                        <div class="d-flex justify-content-center">
                            <div class="col-md-7 mb-1 mt-4 mx-4">
                                <label class="form-label mx-4" for="{{ form.current_password.id_for_lable }}">Введите текущий пароль<span class="txt-headline txt-select">*</span></label>
                                {{ form.current_password }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_current_password_feedback"></div>
                            </div>
                            <div class="col-md-8 mb-1 mt-4 mx-4">
                                <label class="form-label mx-4" for="{{ form.new_password.id_for_lable }}">Введите новый пароль<span class="txt-headline txt-select">*</span></label>
                                {{ form.new_password }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_new_password_feedback"></div>
                                <label class="form-label mx-4 mt-3" for="{{ form.re_new_password.id_for_lable }}">Подтвердите новый пароль<span class="txt-headline txt-select">*</span></label>
                                {{ form.re_new_password }}
                                <div class="invalid-feedback" style="text-transform: lowercase" id="id_re_new_password_feedback"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center pt-4" id="SaveChanges">
                        <button type="submit" id="SaveChangesbtn" class="btn btn-dark btn-block col-5">Сохранить</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block add_scripts %}
    <script src="{% static "js/Users/forms.js" %}"></script>
{% endblock %}

Users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block add_css %}
    <link rel="stylesheet" href="{% static "css/users_forms.css" %}">
    <link rel="stylesheet" href="{% static "css/coupons.css" %}">
{% endblock %}

{% block content %}
<div class="container">
    <img src="{% static 'images/catjpg.jpg' %}" class="bg-profile">
    <div class="my-container mt-3 overflow-y-scroll" style="width: 820px; left: 47%; height:600px;">
        <h3 class="txt-headline text-center pt-5">Ваш профиль</h3>
        <div class="d-flex justify-content-center pt-4 txt-content">
            <div class="col-md-10">
                <div class="tabs justify-content-center">
                    <span class="tab mainInf active txt-headline"><a style="letter-spacing: .05rem">данные профиля</a></span>
                    <span class="tab visits txt-headline"><a style="letter-spacing: .05rem">История посещений</a></span>
                    <span class="tab guardianship txt-headline"><a style="letter-spacing: .05rem">Опекунство</a></span>
                    <span class="tab bonuses txt-headline"><a style="letter-spacing: .05rem">Бонусы</a></span>
                </div>
                <div><span name="user"></span></div>
                    <div class="content">
                        <div class="mainInf-cont cont">
                            <div class="row justify-content-center pt-4 txt-content">
                                <div class="col-md-5">
                                    <label class="mb-2 mx-3 form-label">Имя</label>
                                    <div class="px-3 form-control mb-3" name="username"></div>
                                    <label class="mb-2 mx-3 form-label">Почта</label>
                                    <div class="px-3 form-control mb-3" name="email"></div>
                                </div>
                                <div class="col-md-5">
                                    <label class="mb-2 mx-3 form-label">Телефон</label>
                                    <div class="px-3 form-control mb-3" name="phone"></div>
                                    <label class="mb-2 mx-3 form-label">День рождения</label>
                                    <div class="px-3 form-control mb-3" name="birthday"> </div>
                                </div>
                                <div class="row justify-content-center col-4 pt-5">
                                    {% csrf_token %}
                                    <a class="btn btn-dark btn-block mb-3" href="{% url 'users:change_profile' %}">Изменить профиль</a>
                                    <button id="id_logout" class="btn btn-dark btn-block">Выйти</button>
                                </div>
                            </div>
                        </div>
                        <div class="visits-cont cont">
                            <div class="invisible" id="booking_exists">
                                <div class="txt-content pt-1 d-flex flex-column justify-content-start">
                                    <h4 class="text-center txt-headline fs-5">Ближайшие записи:</h4>
                                    <div class="d-flex flex-column pt-2 booking-near">  
                                        <div id="is_active">
                                            <ul id="append_is_active" class="list-group booking-near pb-2"></ul>
                                        </div>
                                    </div>
                                    <h4 class="text-center txt-headline fs-5">Старые записи:</h4>
                                    <div class="d-flex flex-column pt-2 booking-history">
                                        <div id="isnt_active">
                                            <ul id="append_isnt_active" class="list-group booking-history"></ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="invisible" id="booking_doesnt_exist">
                                <div class="txt-content pt-1 d-flex flex-column align-items-center">
                                    <h4 class="px-3 pb-2 fs-6">Вы к нам еще не приходили :(</h4>
                                    <img src="{% static 'gifs/crying-cat.gif' %}" alt="crying cat" class="crying-gif mb-3">
                                    <a class="btn btn-dark btn-block " href="{% url 'booking:schedule' %}">Исправим?</a>
                                </div>
                            </div>
                        </div>
                        <div class="guardianship-cont cont txt-content">
                            <div class="invisible" id="guardianship_exists">
                                <div class="txt-content pt-1 d-flex flex-column justify-content-start">

                                        <h4 class="text-center txt-headline fs-5">Ваши котики</h4>
                                        <div class="d-flex flex-column pt-3">
                                            <ul id="append_cats" class="list-group">
                                                
                                            </ul>
                                        </div>

                                </div>
                            </div>
                            <div class="invisible" id="guardianship_doesnt_exist">
                                <div class="txt-content pt-1 d-flex flex-column align-items-center">
                                    <h4 class="px-3 pb-2 fs-6">Вы не опекаете еще ни одного котика :(</h4>
                                    <img src="{% static 'gifs/cat_crying_2.gif' %}" alt="crying cat" class="crying-gif mb-3">
                                    <a class="btn btn-dark btn-block" href="{% url 'cats:guardianship' %}">Помочь котикам?</a>
                                </div>
                            </div>
                        </div>
                        <div class="bonuses-cont cont txt-content">
                            <div class="d-flex pt-4">
                                <div class="coins-block mx-5">
                                    <div>
                                        <img src="{% static 'images/catCoin.png' %}" class="img-coins z-2">
                                    </div>
                                    <div class="mx-2">
                                        <div class="px-3 coins" name="coins_count"></div>
                                    </div>
                                </div>
                                <div class="coins-label z-2">
                                    <span class="txt-headline">Мяу</span>коины — бонусная валюта, которую можно получить
                                    <span class="text-wavy">при оплате заказов и услуг</span> на нашем сайте.
                                </div>
                            </div>
                            <div class="mt-4 mx-5 text-center history-coins relative-position">
                                <a class="txt-headline fs-5 history-coins-label">История ваших накоплений</a>
                                <img class="cursor-img" src="{% static 'images/cursor.png' %}">
                                <div class="history-coins-block mt-3">
                                    <div name="history-coins" class="d-flex flex-column justify-content-center align-items-center">
                                    </div>
                                </div>
                            </div>
                            <h4 class="txt-headline fs-4 text-center pt-5">Ваши промокоды и скидки!</h4>
                            <div class="position-relative my-4">
                                <button id="left" class="position-absolute arrow-left">
                                    <img src="{% static 'images/arrow.png' %}" width="72px">
                                </button>
                                <div name="coupons" class="container-cards p-2">
                                </div>
                                <button id="right" class="position-absolute arrow-right">
                                    <img src="{% static 'images/arrow.png' %}" width="72px">
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'users/modal_del_booking.html' %}
{% include 'users/modal_del_sub.html' %}
{% endblock %}

{% block add_scripts %}
    <script src="{% static "js/js-msg.js" %}"></script>
    <script src="{% static "js/Users/get_profile.js" %}"></script>
    <script src="{% static "js/Bonuses/get_coupons.js" %}"></script>
    <script src="{% static "js/Users/profile.js" %}"></script>
    <script src="{% static "js/Bonuses/cards.js" %}"></script>
{% endblock %}