Booking/urls.py
from django.urls import path

from Booking.views import ScheduleView, ScheduleDayAPIView, ScheduleTimeAPIView, BookingAPIView, BookingAPIDelete

app_name = 'booking'

urlpatterns = [
    path('', ScheduleView.as_view(), name='schedule'),
    path('api/schedule/day/', ScheduleDayAPIView.as_view()),
    path('api/schedule/time/', ScheduleTimeAPIView.as_view()),
    path('api/booking/', BookingAPIView.as_view()),
    path('api/booking/<int:pk>', BookingAPIDelete.as_view()),
]

Cats/urls.py
from django.urls import path

from Cats.views import OurCatsView, CatsListAPIView, AdoptView, GiveView, GuardianshipView, AdopAPIView, GiveAPIView, \
    GuardianshipAPIView

app_name = 'cats'


urlpatterns = [
    path('our-cats/', OurCatsView.as_view(), name='our_cats'),
    path('adopt/', AdoptView.as_view(), name='adopt'),
    path('api/adopt/', AdopAPIView.as_view()),
    path('give/', GiveView.as_view(), name='give'),
    path('api/give/', GiveAPIView.as_view()),
    path('guardianship/', GuardianshipView.as_view(), name='guardianship'),
    path('api/guardianship/', GuardianshipAPIView.as_view()),
    path('api/cats/', CatsListAPIView.as_view(), name='cats-list'),
]

Main/urls.py
from django.urls import path

from Main.views import IndexView, InfAboutCafeViewSet, AddressListAPIView

app_name = 'main'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('api/address/', AddressListAPIView.as_view()),
    path('api/information/', InfAboutCafeViewSet.as_view(), name='information'),
]

Users/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from Users.views import (UserProfileTemplateView, UserChangeProfileView, UserLoginRegView, UserAccountAPIView, UserLogoutView,
                         UserResetPasswordView, UserResetNewPasswordView, UserUpdateInfAboutPaymentsView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginRegView.as_view(), name='page_login'),
    path('update/', UserUpdateInfAboutPaymentsView.as_view(), name='update'),
    path('email/reset/', UserResetPasswordView.as_view(), name='reset_password'),
    path('password/reset/confirm/<str:uid>/<str:token>/', UserResetNewPasswordView.as_view(), name='new_password'),
    path('profile/', UserProfileTemplateView.as_view(), name='profile'),
    path('profile/change/', UserChangeProfileView.as_view(), name='change_profile'),
    path('logout/', UserLogoutView.as_view(), name='logout_delToken'),
    path('api/auth/my/profile/', UserAccountAPIView.as_view(), name='account'),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^api/auth/', include('djoser.urls.authtoken')),
]

pawsAndCoffee/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from System.views import tr_handler500, tr_handler403, tr_handler404
from pawsAndCoffee import settings

handler403 = tr_handler403
handler404 = tr_handler404
handler500 = tr_handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),

    path('', include('Main.urls', namespace='main')),
    path('user/', include('Users.urls', namespace='users')),
    path('cats/', include('Cats.urls', namespace='cats')),
    path('calendar/', include('Booking.urls', namespace='booking')),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('bonus/', include('Bonuses.urls', namespace='bonuses'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(r'^403$', TemplateView.as_view(template_name='system/errors/error_page403.html')),
        re_path(r'^404$', TemplateView.as_view(template_name='system/errors/error_page404.html')),
        re_path(r'^500$', TemplateView.as_view(template_name='system/errors/error_page500.html')),
    ]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/null.css' %}">
    <link rel="stylesheet" href="{% static 'css/my_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/png" sizes="320x320" imagesizes="320x320" href="{% static 'favicon/cat-coffe-icon.png' %}">
    {% block add_css %}{% endblock add_css %}
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light txt-headline">
        <div class="container">
            <a class="navbar-brand logo" href="{% url 'main:index' %}">Лапки&Кофе</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:schedule' %}">Онлайн-запись</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cats:our_cats' %}">Наши котики</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:index' %}#about_us">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:index' %}#contacts">Контакты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="
                            {% if request.user.is_authenticated %}
                                {% url 'users:profile' %}
                            {% else %}
                                {% url 'users:page_login'%}
                            {% endif %}
                        ">Личный кабинет</a>
                    </li>
                    {% if request.user.is_authenticated and request.user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Админ-панель</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    </header>
    <section>
        {% include "notifications.html" %}
        {% block content %}{% endblock content %}
    </section>
    <script src="{% static 'js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-plugins/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>
    {% block add_scripts %}{% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/notifications.html
{% load static %}

{% if form.non_field_errors %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{ form.non_field_errors }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification-success" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow"
                 style="display: none;" role="alert"></div>
            <div id="jq-notification-danger" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow"
                 style="display: none;" role="alert"></div>
            {% endif %}
        </div>
    </div>
</div>